
--INSERT INTO ALUMNO (id, name, ap1) VALUES (1, 'PEPE', 'FERNANDEZ')
--INSERT INTO ALUMNO (id, name, ap1) VALUES (2, 'JUAN', 'MARIN')
--INSERT INTO ALUMNO (id, name, ap1) VALUES (3, 'LUIS', 'MARTIN')
--INSERT INTO ALUMNO (id, name, ap1) VALUES (4, 'MARCOS', 'SANCHEZ')
--INSERT INTO ALUMNO (id, name, ap1) VALUES (5, 'ARTURO', 'GONZALEZ')
--INSERT INTO ALUMNO (id, name, ap1) VALUES (6, 'ANTONIO', 'BARRIL')

INSERT INTO ALUMNO (name, ap1) VALUES ('PEPE', 'FERNANDEZ')
INSERT INTO ALUMNO (name, ap1) VALUES ('JUAN', 'MARIN')
INSERT INTO ALUMNO (name, ap1) VALUES ('LUIS', 'MARTIN')
INSERT INTO ALUMNO (name, ap1) VALUES ('MARCOS', 'SANCHEZ')
INSERT INTO ALUMNO (name, ap1) VALUES ('ARTURO', 'GONZALEZ')
INSERT INTO ALUMNO (name, ap1) VALUES ('ANTONIO', 'BARRIL')
